// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {echo} from '../models';

export function ClearEchoLogs():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:number,arg5:config.FramingConfig,arg6:string,arg7:config.ConnectionSettings):Promise<void>;

export function CreateCollection(arg1:string):Promise<void>;

export function DecodeFromHex(arg1:string,arg2:string):Promise<string>;

export function DeleteCase(arg1:string,arg2:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DryRunPostRecvScript(arg1:main.PostRecvDryRunRequest):Promise<main.ScriptDryRunResponse>;

export function DryRunScript(arg1:main.ScriptDryRunRequest):Promise<main.ScriptDryRunResponse>;

export function EncodeToHex(arg1:string,arg2:string):Promise<string>;

export function GetEchoLogs():Promise<Array<echo.LogEntry>>;

export function GetEchoStatus():Promise<echo.Status>;

export function GetScriptVariable(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetSupportedEscapeSequences():Promise<Record<string, string>>;

export function GetSupportedVariables():Promise<Array<string>>;

export function IsConnected(arg1:string):Promise<boolean>;

export function LoadCase(arg1:string,arg2:string):Promise<config.SavedCase>;

export function LoadCollections():Promise<Array<config.CollectionWithCases>>;

export function LoadSettings():Promise<config.AppSettings>;

export function MoveCase(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PreprocessMessage(arg1:string,arg2:boolean):Promise<string>;

export function PreviewMessage(arg1:string):Promise<string>;

export function ProcessMessageWithScripts(arg1:main.ScriptProcessRequest):Promise<string>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function ReorderCases(arg1:string,arg2:Array<config.CaseOrder>):Promise<void>;

export function ReorderCollections(arg1:Array<config.CollectionOrder>):Promise<void>;

export function ResetCounter(arg1:string):Promise<void>;

export function ResetScriptCounter(arg1:string):Promise<void>;

export function SaveCase(arg1:string,arg2:config.SavedCase):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function Send(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetScriptVariable(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function StartEchoServer(arg1:number,arg2:string):Promise<void>;

export function StopEchoServer():Promise<void>;

export function UpdateCharset(arg1:string,arg2:string):Promise<void>;

export function UpdateCollection(arg1:string,arg2:config.Collection):Promise<void>;

export function UpdateFraming(arg1:string,arg2:config.FramingConfig):Promise<void>;

export function ValidateScript(arg1:string):Promise<void>;
