// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearEchoLogs() {
  return window['go']['main']['App']['ClearEchoLogs']();
}

export function Connect(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DecodeFromHex(arg1, arg2) {
  return window['go']['main']['App']['DecodeFromHex'](arg1, arg2);
}

export function DeleteCase(arg1, arg2) {
  return window['go']['main']['App']['DeleteCase'](arg1, arg2);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DryRunPostRecvScript(arg1) {
  return window['go']['main']['App']['DryRunPostRecvScript'](arg1);
}

export function DryRunScript(arg1) {
  return window['go']['main']['App']['DryRunScript'](arg1);
}

export function EncodeToHex(arg1, arg2) {
  return window['go']['main']['App']['EncodeToHex'](arg1, arg2);
}

export function GetEchoLogs() {
  return window['go']['main']['App']['GetEchoLogs']();
}

export function GetEchoStatus() {
  return window['go']['main']['App']['GetEchoStatus']();
}

export function GetScriptVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetScriptVariable'](arg1, arg2, arg3);
}

export function GetSupportedEscapeSequences() {
  return window['go']['main']['App']['GetSupportedEscapeSequences']();
}

export function GetSupportedVariables() {
  return window['go']['main']['App']['GetSupportedVariables']();
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function LoadCase(arg1, arg2) {
  return window['go']['main']['App']['LoadCase'](arg1, arg2);
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function MoveCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveCase'](arg1, arg2, arg3);
}

export function PreprocessMessage(arg1, arg2) {
  return window['go']['main']['App']['PreprocessMessage'](arg1, arg2);
}

export function PreviewMessage(arg1) {
  return window['go']['main']['App']['PreviewMessage'](arg1);
}

export function ProcessMessageWithScripts(arg1) {
  return window['go']['main']['App']['ProcessMessageWithScripts'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function ReorderCases(arg1, arg2) {
  return window['go']['main']['App']['ReorderCases'](arg1, arg2);
}

export function ReorderCollections(arg1) {
  return window['go']['main']['App']['ReorderCollections'](arg1);
}

export function ResetCounter(arg1) {
  return window['go']['main']['App']['ResetCounter'](arg1);
}

export function ResetScriptCounter(arg1) {
  return window['go']['main']['App']['ResetScriptCounter'](arg1);
}

export function SaveCase(arg1, arg2) {
  return window['go']['main']['App']['SaveCase'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Send(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Send'](arg1, arg2, arg3, arg4);
}

export function SetScriptVariable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetScriptVariable'](arg1, arg2, arg3, arg4);
}

export function StartEchoServer(arg1, arg2) {
  return window['go']['main']['App']['StartEchoServer'](arg1, arg2);
}

export function StopEchoServer() {
  return window['go']['main']['App']['StopEchoServer']();
}

export function UpdateCharset(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharset'](arg1, arg2);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2);
}

export function UpdateFraming(arg1, arg2) {
  return window['go']['main']['App']['UpdateFraming'](arg1, arg2);
}

export function ValidateScript(arg1) {
  return window['go']['main']['App']['ValidateScript'](arg1);
}
